name: Build APK Kalkulator Kas

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Mengambil File Repository
      uses: actions/checkout@v4

    - name: Ekstrak File ZIP
      run: unzip KalkulatorKasAPK.zip

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Merakit Aplikasi (Build APK)
      run: |
        cd KalkulatorKasAPK
        gradle assembleDebug

    - name: Menyimpan Hasil APK
      uses: actions/upload-artifact@v4
      with:
        name: Kalkulator-Kas-APK-Siap-Instal
        path: KalkulatorKasAPK/app/build/outputs/apk/debug/*.apk
